version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "18081:18081"
    environment:
      # Logging
      - LOG_JSON=true
      - LOG_LEVEL=INFO

      # Database
      - DATABASE_URL=sqlite+aiosqlite:///./thurup.db

      # CORS - Allow frontend to connect
      - CORS_ORIGINS=http://localhost:5173,http://frontend:5173

      # Admin credentials (change in production!)
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=changeme

      # Cleanup settings (in seconds)
      - CLEANUP_INTERVAL=1800        # 30 minutes
      - LOBBY_TIMEOUT=3600            # 1 hour
      - ACTIVE_TIMEOUT=7200           # 2 hours
      - COMPLETED_TIMEOUT=86400       # 24 hours

      # Game timing
      - TRICK_VIEW_DELAY=2.5
    volumes:
      # Persist database
      - backend-data:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:18081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    environment:
      # Backend API URL
      - VITE_API_BASE_URL=http://localhost:18081
      - VITE_WS_BASE_URL=ws://localhost:18081
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

volumes:
  backend-data:
    driver: local
