[project]
name = "thurup"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.118.3",
    "uvicorn[standard]>=0.37.0",
    "websockets>=15.0.1",
]
