"""Initial SQLModel migration

Revision ID: 22dbfa4b623f
Revises: 
Create Date: 2025-10-13 17:49:19.502647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '22dbfa4b623f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('min_bid', sa.Integer(), nullable=False),
    sa.Column('hidden_trump_mode', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('two_decks_for_56', sa.Boolean(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('current_phase_data', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_state_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('snapshot_data', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state_phase', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('snapshot_reason', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_state_snapshots_game_id'), 'game_state_snapshots', ['game_id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('player_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('seat', sa.Integer(), nullable=False),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_game_id'), 'players', ['game_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_game_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_game_state_snapshots_game_id'), table_name='game_state_snapshots')
    op.drop_table('game_state_snapshots')
    op.drop_table('games')
    # ### end Alembic commands ###
